var modules =
[
    [ "Action Classes", "group__actions.html", null ],
    [ "Base Classes", "group__base.html", null ],
    [ "Bundle Classes", "group__bundles.html", null ],
    [ "Cache Classes", "group__caches.html", null ],
    [ "Detail Classes", "group__details.html", null ],
    [ "Dragger Classes", "group__draggers.html", null ],
    [ "Element Classes", "group__elements.html", null ],
    [ "Engine Classes", "group__engines.html", null ],
    [ "Error Handling Classes", "group__errors.html", null ],
    [ "Event Classes", "group__events.html", null ],
    [ "Field Classes", "group__fields.html", null ],
    [ "Miscellaneous Classes", "group__general.html", null ],
    [ "Manipulator Classes", "group__manips.html", null ],
    [ "Navigation Classes", "group__navigation.html", "group__navigation" ],
    [ "NodeKit Classes", "group__nodekits.html", null ],
    [ "Node Classes", "group__nodes.html", "group__nodes" ],
    [ "Projector Classes", "group__projectors.html", null ],
    [ "Sensor Classes", "group__sensors.html", null ],
    [ "Shader Classes", "group__shaders.html", null ],
    [ "Coin specific State Chart XML Classes", "group__soscxml.html", null ],
    [ "3D Sound Support Classes", "group__sound.html", null ],
    [ "State Chart XML Classes", "group__scxml.html", null ],
    [ "Portable Threads Abstraction Classes", "group__threads.html", null ],
    [ "VRML97 Classes", "group__VRMLnodes.html", null ],
    [ "Vectorized Printing Classes", "group__hardcopy.html", null ],
    [ "XML related functions and objects", "group__XML.html", null ],
    [ "Scene Graph Profiling", "group__profiler.html", null ],
    [ "Miscellaneous Macros", "group__macros.html", null ],
    [ "Miscellaneous Environment Variables", "group__envvars.html", null ],
    [ "Misc", "group__misc.html", "group__misc" ],
    [ "Internal", "group__internal.html", "group__internal" ],
    [ "Action Classes", "../../Coin/html/group__coin__actions.html", null ],
    [ "Base Classes", "../../Coin/html/group__coin__base.html", null ],
    [ "Bundle Classes", "../../Coin/html/group__coin__bundles.html", null ],
    [ "Cache Classes", "../../Coin/html/group__coin__caches.html", null ],
    [ "Detail Classes", "../../Coin/html/group__coin__details.html", null ],
    [ "Dragger Classes", "../../Coin/html/group__coin__draggers.html", null ],
    [ "Element Classes", "../../Coin/html/group__coin__elements.html", null ],
    [ "Engine Classes", "../../Coin/html/group__coin__engines.html", null ],
    [ "Error Handling Classes", "../../Coin/html/group__coin__errors.html", null ],
    [ "Event Classes", "../../Coin/html/group__coin__events.html", null ],
    [ "Field Classes", "../../Coin/html/group__coin__fields.html", null ],
    [ "Miscellaneous Classes", "../../Coin/html/group__coin__general.html", null ],
    [ "Manipulator Classes", "../../Coin/html/group__coin__manips.html", null ],
    [ "Navigation Classes", "../../Coin/html/group__coin__navigation.html", null ],
    [ "NodeKit Classes", "../../Coin/html/group__coin__nodekits.html", null ],
    [ "Node Classes", "../../Coin/html/group__coin__nodes.html", "group__coin__nodes" ],
    [ "Projector Classes", "../../Coin/html/group__coin__projectors.html", null ],
    [ "Sensor Classes", "../../Coin/html/group__coin__sensors.html", null ],
    [ "Shader Classes", "../../Coin/html/group__coin__shaders.html", null ],
    [ "Coin specific State Chart XML Classes", "../../Coin/html/group__coin__soscxml.html", null ],
    [ "3D Sound Support Classes", "../../Coin/html/group__coin__sound.html", null ],
    [ "State Chart XML Classes", "../../Coin/html/group__coin__scxml.html", null ],
    [ "Portable Threads Abstraction Classes", "../../Coin/html/group__coin__threads.html", "group__coin__threads" ],
    [ "VRML97 Classes", "../../Coin/html/group__coin__VRMLnodes.html", null ],
    [ "Vectorized Printing Classes", "../../Coin/html/group__coin__hardcopy.html", null ],
    [ "XML related functions and objects", "../../Coin/html/group__coin__XML.html", "group__coin__XML" ],
    [ "Scene Graph Profiling", "../../Coin/html/group__coin__profiler.html", null ],
    [ "Miscellaneous Macros", "../../Coin/html/group__coin__macros.html", null ],
    [ "Miscellaneous Environment Variables", "../../Coin/html/group__coin__envvars.html", "group__coin__envvars" ]
];