var modules =
[
    [ "Miscellaneous Classes", "group__misc.html", "group__misc" ],
    [ "Win Device Classes", "group__devices.html", "group__devices" ],
    [ "Win Components", "group__components.html", "group__components" ],
    [ "Win Viewer Components", "group__viewers.html", "group__viewers" ],
    [ "Action Classes", "../../Coin/html/group__actions.html", null ],
    [ "Base Classes", "../../Coin/html/group__base.html", null ],
    [ "Bundle Classes", "../../Coin/html/group__bundles.html", null ],
    [ "Cache Classes", "../../Coin/html/group__caches.html", null ],
    [ "Detail Classes", "../../Coin/html/group__details.html", null ],
    [ "Dragger Classes", "../../Coin/html/group__draggers.html", null ],
    [ "Element Classes", "../../Coin/html/group__elements.html", null ],
    [ "Engine Classes", "../../Coin/html/group__engines.html", null ],
    [ "Error Handling Classes", "../../Coin/html/group__errors.html", null ],
    [ "Event Classes", "../../Coin/html/group__events.html", null ],
    [ "Field Classes", "../../Coin/html/group__fields.html", null ],
    [ "Miscellaneous Classes", "../../Coin/html/group__general.html", null ],
    [ "Manipulator Classes", "../../Coin/html/group__manips.html", null ],
    [ "Navigation Classes", "../../Coin/html/group__navigation.html", null ],
    [ "NodeKit Classes", "../../Coin/html/group__nodekits.html", null ],
    [ "Node Classes", "../../Coin/html/group__nodes.html", "group__nodes" ],
    [ "Projector Classes", "../../Coin/html/group__projectors.html", null ],
    [ "Sensor Classes", "../../Coin/html/group__sensors.html", null ],
    [ "Shader Classes", "../../Coin/html/group__shaders.html", null ],
    [ "Coin specific State Chart XML Classes", "../../Coin/html/group__soscxml.html", null ],
    [ "3D Sound Support Classes", "../../Coin/html/group__sound.html", null ],
    [ "State Chart XML Classes", "../../Coin/html/group__scxml.html", null ],
    [ "Portable Threads Abstraction Classes", "../../Coin/html/group__threads.html", "group__threads" ],
    [ "VRML97 Classes", "../../Coin/html/group__VRMLnodes.html", null ],
    [ "Vectorized Printing Classes", "../../Coin/html/group__hardcopy.html", null ],
    [ "XML related functions and objects", "../../Coin/html/group__XML.html", "group__XML" ],
    [ "Scene Graph Profiling", "../../Coin/html/group__profiler.html", "group__profiler" ],
    [ "Miscellaneous Macros", "../../Coin/html/group__macros.html", null ],
    [ "Miscellaneous Environment Variables", "../../Coin/html/group__envvars.html", "group__envvars" ]
];