var modules =
[
    [ "Miscellaneous Classes", "group__misc.html", "group__misc" ],
    [ "Wx Device Classes", "group__devices.html", "group__devices" ],
    [ "Wx Components", "group__components.html", "group__components" ],
    [ "Wx Viewer Components", "group__viewers.html", "group__viewers" ],
    [ "Action Classes", "../../Coin/html/group__coin__actions.html", null ],
    [ "Base Classes", "../../Coin/html/group__coin__base.html", null ],
    [ "Bundle Classes", "../../Coin/html/group__coin__bundles.html", null ],
    [ "Cache Classes", "../../Coin/html/group__coin__caches.html", null ],
    [ "Detail Classes", "../../Coin/html/group__coin__details.html", null ],
    [ "Dragger Classes", "../../Coin/html/group__coin__draggers.html", null ],
    [ "Element Classes", "../../Coin/html/group__coin__elements.html", null ],
    [ "Engine Classes", "../../Coin/html/group__coin__engines.html", null ],
    [ "Error Handling Classes", "../../Coin/html/group__coin__errors.html", null ],
    [ "Event Classes", "../../Coin/html/group__coin__events.html", null ],
    [ "Field Classes", "../../Coin/html/group__coin__fields.html", null ],
    [ "Miscellaneous Classes", "../../Coin/html/group__coin__general.html", null ],
    [ "Manipulator Classes", "../../Coin/html/group__coin__manips.html", null ],
    [ "Navigation Classes", "../../Coin/html/group__coin__navigation.html", null ],
    [ "NodeKit Classes", "../../Coin/html/group__coin__nodekits.html", null ],
    [ "Node Classes", "../../Coin/html/group__coin__nodes.html", "group__coin__nodes" ],
    [ "Projector Classes", "../../Coin/html/group__coin__projectors.html", null ],
    [ "Sensor Classes", "../../Coin/html/group__coin__sensors.html", null ],
    [ "Shader Classes", "../../Coin/html/group__coin__shaders.html", null ],
    [ "Coin specific State Chart XML Classes", "../../Coin/html/group__coin__soscxml.html", null ],
    [ "3D Sound Support Classes", "../../Coin/html/group__coin__sound.html", null ],
    [ "State Chart XML Classes", "../../Coin/html/group__coin__scxml.html", null ],
    [ "Portable Threads Abstraction Classes", "../../Coin/html/group__coin__threads.html", "group__coin__threads" ],
    [ "VRML97 Classes", "../../Coin/html/group__coin__VRMLnodes.html", null ],
    [ "Vectorized Printing Classes", "../../Coin/html/group__coin__hardcopy.html", null ],
    [ "XML related functions and objects", "../../Coin/html/group__coin__XML.html", "group__coin__XML" ],
    [ "Scene Graph Profiling", "../../Coin/html/group__coin__profiler.html", null ],
    [ "Miscellaneous Macros", "../../Coin/html/group__coin__macros.html", null ],
    [ "Miscellaneous Environment Variables", "../../Coin/html/group__coin__envvars.html", "group__coin__envvars" ]
];