var modules =
[
    [ "Miscellaneous Classes", "group__misc.html", "group__misc" ],
    [ "Qt Device Classes", "group__devices.html", "group__devices" ],
    [ "Qt Components", "group__components.html", "group__components" ],
    [ "Qt Viewer Components", "group__viewers.html", "group__viewers" ],
    [ "Action Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__actions.html", null ],
    [ "Base Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__base.html", null ],
    [ "Bundle Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__bundles.html", null ],
    [ "Cache Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__caches.html", null ],
    [ "Detail Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__details.html", null ],
    [ "Dragger Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__draggers.html", null ],
    [ "Element Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__elements.html", null ],
    [ "Engine Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__engines.html", null ],
    [ "Error Handling Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__errors.html", null ],
    [ "Event Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__events.html", null ],
    [ "Field Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__fields.html", null ],
    [ "Miscellaneous Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__general.html", null ],
    [ "Manipulator Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__manips.html", null ],
    [ "Navigation Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__navigation.html", null ],
    [ "NodeKit Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__nodekits.html", null ],
    [ "Node Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__nodes.html", "group__nodes" ],
    [ "Projector Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__projectors.html", null ],
    [ "Sensor Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__sensors.html", null ],
    [ "Shader Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__shaders.html", null ],
    [ "Coin specific State Chart XML Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__soscxml.html", null ],
    [ "3D Sound Support Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__sound.html", null ],
    [ "State Chart XML Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__scxml.html", null ],
    [ "Portable Threads Abstraction Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__threads.html", "group__threads" ],
    [ "VRML97 Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__VRMLnodes.html", null ],
    [ "Vectorized Printing Classes", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__hardcopy.html", null ],
    [ "XML related functions and objects", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__XML.html", "group__XML" ],
    [ "Scene Graph Profiling", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__profiler.html", "group__profiler" ],
    [ "Miscellaneous Macros", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__macros.html", null ],
    [ "Miscellaneous Environment Variables", "C:/Data/Volker/Github/installed/share/doc/Coin/html/group__envvars.html", "group__envvars" ]
];